rust: stable
language: rust

script:
  - cargo build
  - cargo test

matrix:
  include:
    # Linux
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    # macOS
    - os: osx
      env: TARGET=x86_64-apple-darwin
    # Windows
    - os: windows
      env: TARGET=x86_64-pc-windows-gnu

install:
  - rustup target add $TARGET

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

before_deploy:
  - |
    (
    cargo build --release --target $TARGET -- -C lto
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      7z a "lethe-${TRAVIS_TAG}-${TARGET}.exe" ./target/${TARGET}/release/lethe.exe
    else
      tar -C target/${TARGET}/release -czf lethe-${TRAVIS_TAG}-${TARGET}.tar.gz lethe
    fi
    )

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: "FpssqeCvG1gGeZ+YblYfBHGAQoK5IaNuPVIv5TcMUrLKutYpbytHii6J5xvYZ0xeVCaksnEuAt0Is6/Qwce68LmJEU8lYntPNlaVJ/tg5+9iqMID3QPHIhCio1hHj9npsnpVBI4MwmxqAH5Y5V6PifmiaKmEj7PJkZMwimMAdUnBbuCA+F9Sfa+oiFp41n1FwGXELWV7HA6qN1Qk16BpN06CKChUPQjjtVEoon+rXUjM4SiXG+94I64YLSZw6rLPs8ksiV6yEAwvbtO1J4BgneChoxZiyCbbXB1EkHdU+eC5nSGq2Cjgg4bnVL307GfxlzbuxBwgEAO6qA62TYfONPZdAilBMGgQcSigUFRpz7VNrXKBL36Zem084hXrT4sh99THs14rPt06QtVfKLdqMDLbtfdv2WnG5F5BBOilflwFed0oms9jl3r74GG8H3R0ThYlL8F75AN1tEFdoiapFm0wXcf5EIvZR5jpW/tVQ0o4BMNjFF0VFddPfVvfM9sQiTj4FZ1EhiyJDB1yivyyEl/f4dwPv9gTwuxUcsYGI9axSMJyfW9+Vt05xi0hqGtC5b+mnOXVc2DACMCKphQHMqRmtCoGE4o5F7KN3erVmphZfv26L8oaAjBmWpsh12V7YL/AbL20G7db3Hf5UkY7iPPSJrk08dAsxmI4kL0o+Rc="
  file: lethe-$TRAVIS_TAG-$TARGET*
  on:
    repo: Kostassoid/lethe
    tags: true
    branch: master

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags.
    # Required, or travis won't trigger deploys when a new tag is pushed.
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_success: never
