[package]
name = "lethe"
version = "0.1.0"
authors = ["kostassoid <k.alexandroff@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.14.1"
clap = "~2.33"
rand = "0.6"
indicatif = "0.11.0"
console = "0.7.7"

[dev-dependencies]
flate2 = "1.0"